"""Neutral domain entities — no broker-specific types leak here.

All monetary values use Decimal. Datetime fields are always timezone-aware.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from app.core.enums import (
    AssetClass,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionSide,
    SignalSide,
    TimeInForce,
)
from app.core.exceptions import LookAheadError


class Instrument(BaseModel):
    """A tradable instrument."""

    symbol: str
    asset_class: AssetClass
    provider_name: str
    tick_size: Optional[Decimal] = None
    min_qty: Optional[Decimal] = None
    active: bool = True

    @field_validator("symbol")
    @classmethod
    def symbol_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("symbol cannot be empty")
        return v.upper()


class Candle(BaseModel):
    """OHLCV bar. is_closed=True means the bar has fully formed."""

    time: datetime          # bar open time (timezone-aware)
    symbol: str
    timeframe: str          # e.g. "15m", "1h", "1d"
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal
    is_closed: bool = True  # False = bar still forming (must never reach generate_signal)

    @model_validator(mode="after")
    def validate_ohlc(self) -> "Candle":
        if self.high < self.open or self.high < self.close or self.high < self.low:
            raise ValueError(f"high {self.high} must be >= open, close, and low")
        if self.low > self.open or self.low > self.close or self.low > self.high:
            raise ValueError(f"low {self.low} must be <= open, close, and high")
        if self.volume < 0:
            raise ValueError("volume cannot be negative")
        return self

    def assert_closed(self) -> None:
        """Raise LookAheadError if this candle is not yet closed."""
        if not self.is_closed:
            raise LookAheadError(
                f"Candle {self.symbol} at {self.time} is not yet closed — "
                "using it for signal generation would introduce look-ahead bias."
            )


class OrderRequest(BaseModel):
    """Neutral order request sent to a BrokerProvider."""

    client_order_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    side: OrderSide
    type: OrderType
    qty: Decimal
    limit_price: Optional[Decimal] = None
    stop_price: Optional[Decimal] = None
    time_in_force: TimeInForce = TimeInForce.DAY
    strategy_name: Optional[str] = None
    instrument: Optional[Instrument] = None
    extended_hours: bool = False

    # Optional bracket order legs.
    # When both are set the order is submitted as a bracket (OCO) order:
    # the broker attaches a stop-loss sell and a take-profit limit sell.
    stop_loss_price: Optional[Decimal] = None
    take_profit_price: Optional[Decimal] = None

    @field_validator("qty")
    @classmethod
    def qty_positive(cls, v: Decimal) -> Decimal:
        if v <= 0:
            raise ValueError(f"qty must be positive, got {v}")
        return v


class OrderAck(BaseModel):
    """Broker acknowledgement of an order submission."""

    client_order_id: str
    broker_order_id: str
    status: OrderStatus
    symbol: str
    side: OrderSide
    type: OrderType
    qty: Decimal
    filled_qty: Decimal = Decimal("0")
    avg_fill_price: Optional[Decimal] = None
    submitted_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    error_message: Optional[str] = None


class Position(BaseModel):
    """Current broker position for a symbol."""

    symbol: str
    qty: Decimal                    # positive = long, negative = short
    avg_entry_price: Decimal
    current_price: Optional[Decimal] = None
    unrealized_pnl: Optional[Decimal] = None
    side: PositionSide = PositionSide.LONG

    @property
    def market_value(self) -> Optional[Decimal]:
        if self.current_price is None:
            return None
        return abs(self.qty) * self.current_price

    @property
    def is_flat(self) -> bool:
        return self.qty == Decimal("0")


class Account(BaseModel):
    """Broker account summary."""

    equity: Decimal
    cash: Decimal
    buying_power: Decimal
    currency: str = "USD"
    day_trade_count: int = 0            # for PDT compliance
    pattern_day_trader: bool = False


class Fill(BaseModel):
    """A single fill event from the broker."""

    client_order_id: str
    broker_order_id: str
    symbol: str
    qty: Decimal
    price: Decimal
    side: OrderSide
    timestamp: datetime
    fee: Decimal = Decimal("0")


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    strategy_name: str
    instrument: Instrument
    side: SignalSide
    reason: str
    context: dict[str, Any] = Field(default_factory=dict)   # indicator snapshot
    time: datetime                  # time of the last closed candle
    executed: bool = False
    rejected_reason: Optional[str] = None


class Trade(BaseModel):
    """A completed round-trip trade (entry + exit)."""

    strategy_name: str
    instrument: Instrument
    entry_time: datetime
    exit_time: datetime
    entry_price: Decimal
    exit_price: Decimal
    qty: Decimal
    side: OrderSide
    pnl_gross: Decimal
    pnl_net: Decimal
    fees: Decimal = Decimal("0")
    duration_seconds: int
    mode: str                       # "paper" | "live"

    @property
    def is_winner(self) -> bool:
        return self.pnl_net > Decimal("0")
